export const GET_ACCOUNT_DATA = "GET_ACCOUNT_DATA";
export const PAYMENT_HISTORY = "PAYMENT_HISTORY";
export const GET_PAYMENT_TYPE_DETAILS = "GET_PAYMENT_TYPE_DETAILS";
export const GET_HOW_IT_WORKS_CMS_DATA = "GET_HOW_IT_WORKS_CMS_DATA";
