name: deploy-prod-app

on:
  push:
    branches:
      - master
    
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - uses: actions/checkout@master
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Application
        run: CI='' npm run build
        
      - uses: jakejarvis/s3-sync-action@master
        name: Upload App to S3 Production Bucket
        with:
          args: --follow-symlinks --delete --cache-control max-age=86400000
        env:
          AWS_S3_BUCKET: 'claritycooperative.com'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: 'build'
          
      - name: Create CloudFront Cache Invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: 'E3OYG1BZREZ17M'
          PATHS: '/*'
          AWS_REGION: 'us-east-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
